services:
  lfy-scrapper-web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lfy-scrapper-web-prod
    restart: always
    volumes:
      # Only mount data directory in production
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    # Production command - no file watching
    command: ["python", "/app/src/run.py"]

    # Resource limits for production
    # deploy:
    #   resources:
    #     limits:
    #       memory: 4G
    #       cpus: "2.0"
    #     reservations:
    #       memory: 1G
    #       cpus: "0.5"

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s

    networks:
      - prod-network

    # Logging configuration
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

networks:
  prod-network:
    driver: bridge
